name: Regularly task notification

on:
  schedule:
    - cron: '30 10 * * 1-5' # 日本時間で平日の19時半
    - cron: '0 0 * * 1-5' # 日本時間で平日の9時

env:
  NOTION_AUTH_KEY: ${{secrets.NOTION_AUTH_KEY}}
  NOTION_DATABASE_ID: ${{secrets.NOTION_DATABASE_ID}}
  SLACK_API_TOKEN: ${{secrets.SLACK_API_TOKEN}}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Send to slack
        run: |
          npm install
          npm run start